# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GeoGebra.GeoGebraClassic
PackageVersion: 6.0.652
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-652-0.exe
  InstallerSha256: 7207146C432E80721A1F37CED022C78C7409B31BBA8B63142CBD4AC83B5422F7
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
