# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Streamlabs.StreamlabsOBS
PackageVersion: 1.3.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+1.3.0.exe
  InstallerSha256: 85D083056BA82B9256C58E98069D685E7519926014FA5B18C4A8323E0A8AF89F
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
