# Created using YamlCreate.ps1 v1.1.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: baidu.baidunetdisk
PackageVersion: 7.4.3
PackageLocale: zh-CN
Publisher: 北京度友科技有限公司
PublisherUrl: https://www.baidu.com/
PublisherSupportUrl: http://yun.baidu.com/disk/help
PrivacyUrl: http://yun.baidu.com/disk/privacy
Author: 北京度友科技有限公司
PackageName: 百度网盘
PackageUrl: https://pan.baidu.com
License: 专有软件
LicenseUrl: https://pan.baidu.com/disk/duty/
Copyright: 版权所有 (c) 百度公司 
CopyrightUrl: https://ir.baidu.com/notice-right-holders-block-0
ShortDescription: 海量云储存文件，释放本地空间，支持超大文件批量下载和断点续传。
Description: 百度网盘个人版是百度面向个人用户的网盘存储服务，满足用户工作生活各类需求，已上线的产品包括网盘、个人主页、群组功能、通讯录、相册、人脸识别、文章、记事本、短信、手机找回。
Tags:
- 云
- 网盘
- 分享它
- 下载
- 云盘
ManifestType: locale
ManifestVersion: 1.0.0

