# Automatically updated by the winget bot at 2021/Jul/13
PackageIdentifier: SystweakSoftware.AdvancedDriverUpdater
PackageVersion: 4.5.1086.18003
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://cdn.systweak.com/setups/baps/adug_systweak-default.exe?of=adug.exe
  InstallerSha256: F9ADE7951FF19EE70034512149C3A57EC8EEBD297D26AEF5D8838A844CF2BD2A
ManifestType: installer
ManifestVersion: 1.0.0
