# Automatically updated by the winget bot at 2021/Jul/13
PackageIdentifier: SystweakSoftware.AdvancedDriverUpdater
PackageVersion: 4.5.1086.18003
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
