# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: RoyalApps.RoyalTS
PackageVersion: 6.0.50710.0
PackageName: Royal TS
Publisher: Royal Apps GmbH
License: Copyright 2021 Royal Apps GmbH
LicenseUrl: https://support.royalapps.com/support/solutions/articles/17000074360
Moniker: royalts
Tags:
- Remote Desktop
ShortDescription: Using RDP, VNC, SSH based terminals, S/FTP or web-based interfaces
PackageUrl: https://www.royalapps.com/ts/win/features
Installers:
- Architecture: x64
  InstallerUrl: https://download.royalapps.com/RoyalTS/RoyalTSInstaller_6.00.50710.0.msi
  InstallerSha256: E248A8B645AC3A57D2FC924E00225D3524199E6C4361673CB260056238FC5763
  InstallerType: msi
  ProductCode: '{2408F291-807B-43A8-9731-61C35FEB3E1B}'
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
