# Automatically updated by the winget bot at 2021/Jul/13
PackageIdentifier: Axosoft.GitKraken
PackageName: GitKraken
PackageVersion: 7.7.0
Publisher: Axosoft, LLC
PackageUrl: https://www.gitkraken.com/
ShortDescription: Git GUI Client.
License: Commercial (c) 2020 Axosoft, LLC.
LicenseUrl: https://www.gitkraken.com/eula
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://release.axocdn.com/win64/GitKrakenSetup.exe
  InstallerSha256: 64FF6B5E57BC0837580A1547F8A859570C373769031D19A4FC0EF136739C7F27
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
