# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SartoxOnlyGNU.Audacium
PackageVersion: 3.0.4
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/SartoxOnlyGNU/audacium/releases/download/18fbae6/audacium-win-3.0.4-x64.exe
  InstallerSha256: F7EAD1DCFC343F1CB660095A44F4CE517525E7FB47C30253EFBB11511CB177F4
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
