# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: plex.plexmediaserver
PackageVersion: 1.23.4.4805
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
    MinimumVersion: 14.28.29913.0
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://downloads.plex.tv/plex-media-server-new/1.23.4.4805-186bae04e/windows/PlexMediaServer-1.23.4.4805-186bae04e-x86.exe
  InstallerSha256: D23471178873E53BE9C09A3B51E75669238D44345ED11CD8545645D52DB3881F
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

