PackageIdentifier: BiglySoftware.BiglyBT
PackageVersion: 2.8.0.0
Commands:
- BiglyBT
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- magnet
- dht
FileExtensions:
- torrent
- biglybt
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BiglySoftware/BiglyBT/releases/download/v2.8.0.0/GitHub_BiglyBT_Installer64_J14.exe
  InstallerSha256: 034cd1d1fe481266eeba1cb8ac8cd027fab0dc02007fd92caf5dd765db6faf03
  InstallerType: exe
  ProductCode: "0112-2557-8304-7048"
  InstallerSwitches:
    Silent: -q
    Log: -Dinstall4j.log="<LOGPATH>"
    InstallLocation: -dir "<INSTALLPATH>"
ManifestType: installer
ManifestVersion: 1.0.0
