# Automatically updated by the winget bot at 2021/Jul/13
PackageIdentifier: WhatsApp.WhatsApp
PackageVersion: 2.2126.11
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
  InstallerSha256: 3D82CCBC5C72ED4E9F1FAB0B81092E23E765D97C888C2D0786E0579D0B7C06C2
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/ia32/WhatsAppSetup.exe
  InstallerSha256: D8A71E598A19678D50BA5C336D24FFE7C1B095778FD3BD5F358D04A140C41B06
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
