# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: sbt.sbt
PackageVersion: 1.5.5
PackageLocale: en-US
Publisher: Lightbend, Inc.
PackageName: sbt
PackageUrl: https://www.scala-sbt.org/
License: BSD 3 Clause
LicenseUrl: https://raw.githubusercontent.com/sbt/sbt/v1.5.2/LICENSE
ShortDescription: A build tool for Scala, Java, and more
Moniker: sbt
Tags:
- sbt
- scala
- java
- functional
- programming
- language
- admin
ManifestType: defaultLocale
ManifestVersion: 1.0.0

