# Created using YamlCreate.ps1 v1.1.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: LINQPad.LINQPad.6
PackageVersion: 6.14.10
MinimumOSVersion: 10.0.0.0
FileExtensions:
- LINQ
InstallModes:
- interactive
- silent
- silentWithProgress
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.dotnetRuntime.3-x64
Installers:
- Platform:
  - Windows.Desktop
  InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://linqpad.azureedge.net/public/LINQPad6Setup.exe
  InstallerSha256: 48923F058D2EC96B14797240807ED23913F66AAD82675DE78A3373196B3E5A89
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

